
package com.epam.testappservice.service.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FetchByIdException", targetNamespace = "http://service.testappservice.epam.com/")
public class FetchByIdException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.epam.testappservice.service.FetchByIdException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FetchByIdException(String message, com.epam.testappservice.service.FetchByIdException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FetchByIdException(String message, com.epam.testappservice.service.FetchByIdException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epam.testappservice.service.FetchByIdException
     */
    public com.epam.testappservice.service.FetchByIdException getFaultInfo() {
        return faultInfo;
    }

}
